language: ruby
sudo: false
rvm:
- 2.2.4
- 2.3.1
- jruby-9.0.5.0
env:
  global:
  - secure: kbtX4GU9V2DbsKoQ0l2rt9ztm3Tjzs/AGkUHkTKZKH0I9J615xoMtP8f3rHk8p4LCRdsqu6djhJd+P0rNAnu6LtQloovnJRFsVf5CMgKoyozOAfjQc1ybBtA/BFzh+XvyOVFJt9QdDtGp88ES04pYQKFud9Ydgcvse8P1yoO/nTT/NCykbfgHytwvNWQ+xLtcrKxYcbn2wFVZA3umym/uioTxTOQdqJB37JCAAuk+0kRiAEPZXUX7n54wsoWSgEVx3fWGjL6mrdJwtaTgX89JSj+GmPZCJK1pMT8VFWNjp4XfeDwdiA4J6VDaXjV0yas9IlMHGe4YmcU539AsifrUFkKpldVXaciLefIgec6sVYG0mgrm3XRUdTcd6ax9pKQ5z0LkC9wvP+djnQPKqnj8mHuGZiUqdmSaEnyr7gPDi72FBsk1Bya3xW4vZ4UzW/ebzbGOsIKGnE4Q4Fq7a/4mTvreKOsL1AnamHedpfyWEpMAC8zlmQVL1bblFXjRlFKfujkXLr7r1Bzpn8ydXvy22Tvsy5uPYMJDF95QQirVZNgYOxtNEl8Chz8yYXMNw2h+u+u38/BrTKndb+JtXqmoYvgvGpaTwaXBeNowWAmKeu5T4o4ZQAjxj79HqAMZPhQeCelFpJxN9QYjn0PBD1qZ5QWGGsDe0pEXyEOc7lzh/c=
deploy:
- provider: releases
  file: pkg/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: form3tech/pact-mock_service
after_deploy:
- bundle exec rake generate_release_notes[$TRAVIS_TAG]
- bundle exec rake upload_release_notes[$TRAVIS_REPO_SLUG,$TRAVIS_TAG]
